# Config for barrel command
BARREL_DIR := lib
BARREL_FILE := barrel.dart
BARREL_PATH := $(BARREL_DIR)/$(BARREL_FILE)
FIND_CMD := find $(BARREL_DIR)/ -mindepth 1 -name '*.dart' -not -path "$(BARREL_PATH)"

info:
	echo "make reset           - flutter clean ; flutter pub get"
	echo "make barrel          - update the $(BARREL_FILE) file in $(BARREL_PATH)"

.SILENT:

.PHONY: reset barrel

reset:
	flutter clean ; flutter pub get

barrel:
	figlet -f smslant "Generating barrel"
	echo "Adding files to $(BARREL_PATH)..."
	@(	\
		echo "// Auto-generated by 'make barrel'. Do not edit directly."; \
		echo "// To update, run 'make barrel'."; \
		echo "// Exporting all files from: $(BARREL_DIR)"; \
		echo ""; \
		$(FIND_CMD) | sed "s#^$(BARREL_DIR)/##" | sort | sed "s#.*#export '&';#" || true \
	) > "$(BARREL_PATH)" 
	echo "✅ Barrel file '$(BARREL_PATH)' generated successfully."
