// Auto-generated by 'make barrel'. Do not edit directly.
// To update, run 'make barrel'.
// Exporting all files from: lib

export 'app.dart';
export 'barrel_flutter.dart';
export 'base_extensions.dart';
export 'database/database.dart';
export 'main.dart';
export 'models/budget_item.dart';
export 'providers/budget_provider.dart';
export 'views/home_view.dart';
export 'widgets/enter_info_tile.dart';
export 'widgets/expense_item.dart';
export 'widgets/fab.dart';
